services:
  todo-list:
    image: todo-list
    container_name: todo-list
    ports:
      - "5431:8080"
    links: 
      - "db:database"
    build:
      context: .
      dockerfile: TodoList.Api/Dockerfile
  db:
    image: postgres:latest
    container_name: todo-list-db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: todo-list 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo-list-db
      PGDATA: /var/lib/postgresql/data/pgdata
  db-apply-migrations:
    image: postgres:latest
    container_name: todo-list-db-apply-migrations
    restart: "no"
    depends_on:
      - db
    volumes:
      - ./TodoList.Api/Database/Migrations:/migrations
    links:
      - "db:database"
    entrypoint: [ "sh", "-c", "migrations/apply_migrations.sh" ]
    environment:
      POSTGRES_USER: todo-list
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo-list-db 
      
volumes:
  pgdata:
    driver: local